### ISSUE TITLE
cannot login to openshift jenkins after plugin update

### ISSUE THREAD

**Issue by ericfaure007** [openshift/jenkins-openshift-login-plugin#171]
After updating openshift-login jenkins plugin to the latest version, I wasn't able to login to jenkins via oauth.
The update itself was successful.

openshift version: 4.12.27
jenkins version: 2.401.1
openshift-login plugin: 1.1.0.246.v4cf866d36639

Reverting the plugin to the previous running version fixed the problem: 
openshift-login plugin: 1.1.0.227.v27e08dfb_1a_20

jenkins pod Error logs when trying to authenticate on jenkins:
2023-08-16 06:51:20 WARNING org.eclipse.jetty.server.handler.ContextHandler$Context log Error while serving https://jenkins-url/securityRealm/commenceLogin
java.lang.reflect.InvocationTargetException
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:401)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)
...
Caused by: java.net.MalformedURLException: invalid redirect https://jenkins-url/securityRealm/commenceLogin?from=%2F
        at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.doCommenceLogin(OpenShiftOAuth2SecurityRealm.java:1078)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
        ... 106 more
2023-08-16 06:51:20 WARNING hudson.init.impl.InstallUncaughtExceptionHandler handleException Caught unhandled exception with ID 79c14188-7b95-43c4-9b3a-457ef18a23a9
java.net.MalformedURLException: invalid redirect https://jenkins-url/securityRealm/commenceLogin?from=%2F
        at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.doCommenceLogin(OpenShiftOAuth2SecurityRealm.java:1078)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
...

**Comment by ericfaure007** [comment]
After upgrading from openshift 4.12 to 4.13, the problem doesn't occur anymore.
Jenkins version has been upgraded from registry.redhat.io/ocp-tools-4/jenkins-rhel8:v4.12.0 to registry.redhat.io/ocp-tools-4/jenkins-rhel8:v4.13.0.
