### ISSUE TITLE
openshift-login-plugin doesn't work with IBM JDK 8.

### ISSUE THREAD

**Issue by jerboaa** [openshift/jenkins-openshift-login-plugin#23]
I've tried running this plugin on IBM JDK 8 and I'm getting:

    Sep 26, 2017 1:45:55 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
    INFO: populateDefaults
    javax.net.ssl.SSLException: Received fatal alert: protocol_version
            at com.ibm.jsse2.k.a(k.java:25)
            at com.ibm.jsse2.k.a(k.java:3)
            at com.ibm.jsse2.at.b(at.java:49)
            at com.ibm.jsse2.at.a(at.java:573)
            at com.ibm.jsse2.at.i(at.java:73)
            at com.ibm.jsse2.at.a(at.java:357)
            at com.ibm.jsse2.at.startHandshake(at.java:723)
            at com.ibm.net.ssl.www2.protocol.https.c.afterConnect(c.java:215)
            at com.ibm.net.ssl.www2.protocol.https.d.connect(d.java:34)
            at com.ibm.net.ssl.www2.protocol.https.b.connect(b.java:49)
            at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:93)
            at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
            at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.getOpenShiftUserInfo(OpenShiftOAuth2SecurityRealm.java:489)
            at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.populateDefaults(OpenShiftOAuth2SecurityRealm.java:337)
            at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.<init>(OpenShiftOAuth2SecurityRealm.java:273)
            at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftSetOAuth.setOauth(OpenShiftSetOAuth.java:69)
            at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftSetOAuth.setOauth(OpenShiftSetOAuth.java:46)
            at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftItemListener.onLoaded(OpenShiftItemListener.java:41)
            at jenkins.model.Jenkins.<init>(Jenkins.java:998)
            at hudson.model.Hudson.<init>(Hudson.java:86)
            at hudson.model.Hudson.<init>(Hudson.java:82)
            at hudson.WebAppMain$3.run(WebAppMain.java:231)

This is apparently caused by google-oauth-client-java6 using `SSLContext.getInstance("TLS")` somewhere which behaves differently on OpenJDK and IBM JDK. Setting `-Dcom.ibm.jsse2.overrideDefaultTLS=true` fixes it. See:
https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/matchsslcontext_tls.html

**Comment by gabemontero** [comment]
thanks for the report and work around info @jerboaa 

at first blush this seems like a README update candidate

I wouldn't be half surprised if there is some impact with the our original openshift jenkins plugin and openshift sync plugin

@bparees - thoughts on an overall assessment of running our jenkins stuff on the IBM JDK, and any efforts toward "supporting" running on IBM JDK (especially given some of the performance reports we've seen recently)?

**Comment by bparees** [comment]
> @bparees - thoughts on an overall assessment of running our jenkins stuff on the IBM JDK, and any efforts toward "supporting" running on IBM JDK (especially given some of the performance reports we've seen recently)?

yeah we should create a card to go do that and try to get/stay ahead of people hitting this.

**Comment by bparees** [comment]
and +1 on a readme update for now.

**Comment by gabemontero** [comment]
card https://trello.com/c/Gmc0sBIt/1393-jenkinsintegration-assess-openshift-jenkins-functionality-against-the-ibm-jdk created
